# Generated by Django 4.0.1 on 2022-01-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=24)),
                ('cocktail_description', models.TextField(blank=True, default=True)),
                ('cocktail_photo', models.ImageField(upload_to='image/cocktails_photo/')),
                ('cocktail_price_bar', models.IntegerField()),
                ('cocktail_price_employee', models.IntegerField()),
                ('cocktail_price_club', models.IntegerField()),
            ],
        ),
    ]
