# Generated by Django 4.0.1 on 2022-01-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_photo',
            field=models.ImageField(upload_to='cocktails_photo/'),
        ),
    ]
