# Generated by Django 4.0.1 on 2022-01-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0002_alter_cocktail_cocktail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_photo',
            field=models.ImageField(upload_to='audit_site_1/media/image/cocktails_photo/%Y/%m/%d/'),
        ),
    ]
