# Generated by Django 4.0.1 on 2022-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0003_alter_cocktail_cocktail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='cocktail_name',
            field=models.CharField(max_length=32),
        ),
    ]
