# Generated by Django 4.0.1 on 2022-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0005_rename_cocktail_price_bar_cocktail_bar_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'verbose_name': 'Cocktail'},
        ),
    ]
