# Generated by Django 4.0.1 on 2022-02-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0006_alter_cocktail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ['bar_price'], 'verbose_name': 'Коктейль', 'verbose_name_plural': 'Коктейли'},
        ),
    ]
