# Generated by Django 4.0.1 on 2022-02-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0008_alter_cocktail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktail',
            options={'ordering': ['id'], 'verbose_name': 'Коктейль', 'verbose_name_plural': 'Список коктейлей'},
        ),
    ]
