# Generated by Django 4.0.1 on 2022-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0009_alter_cocktail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='customer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='bar_price',
            field=models.IntegerField(verbose_name='Цена в меню'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='club_price',
            field=models.IntegerField(verbose_name='Доля клуба'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='description',
            field=models.TextField(blank=True, default=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='employee_price',
            field=models.IntegerField(verbose_name='Доля сотрудника?'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название коктейля'),
        ),
    ]
