# Generated by Django 4.0.1 on 2022-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0010_cocktail_customer_price_alter_cocktail_bar_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='customer_price',
            field=models.IntegerField(default=0, verbose_name='Доля заказчика(заведения)'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='employee_price',
            field=models.IntegerField(verbose_name='Доля сотрудника'),
        ),
    ]
