# Generated by Django 4.0.1 on 2022-02-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0012_category_cocktail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Наличие на баре'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cocktails_app.category', verbose_name='Вид коктейля'),
        ),
    ]
