# Generated by Django 4.0.1 on 2022-02-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails_app', '0013_cocktail_is_active_alter_cocktail_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Вид коктейля', 'verbose_name_plural': 'Виды коктейлей'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Вид коктейля'),
        ),
    ]
