# Generated by Django 4.0.1 on 2022-01-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=24)),
                ('cocktail_description', models.TextField(blank=True, null=True)),
                ('cocktail_photo', models.ImageField(upload_to='image/cocktails_photo/')),
                ('cocktail_price_bar', models.IntegerField()),
                ('cocktail_price_employee', models.IntegerField()),
                ('cocktail_price_club', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('position', models.CharField(max_length=24)),
                ('pnone_number', models.IntegerField()),
                ('e_mail', models.CharField(max_length=24)),
                ('url', models.CharField(max_length=24)),
                ('rate', models.IntegerField()),
                ('interest_50', models.IntegerField()),
                ('interest_bar', models.IntegerField()),
                ('photo', models.ImageField(upload_to='image/employee_photo/')),
                ('reason_of_disemployment', models.TextField(max_length=256)),
                ('notes', models.TextField(max_length=256)),
            ],
        ),
    ]
