# Generated by Django 4.0.1 on 2022-01-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_rename_pnone_number_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cocktail',
        ),
    ]
