# Generated by Django 4.0.1 on 2022-01-27 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
