# Generated by Django 4.0.1 on 2022-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/image/employee_photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='video',
            field=models.FileField(blank=True, upload_to='media/video/employee_video/%Y/%m/%d/'),
        ),
    ]
