# Generated by Django 4.0.1 on 2022-02-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_alter_employee_photo_alter_employee_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['created_at'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Список сотрудников'},
        ),
    ]
