# Generated by Django 4.0.1 on 2022-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0011_alter_employee_options_alter_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Процент от кассы'),
        ),
    ]
