# Generated by Django 4.0.1 on 2022-02-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0012_employee_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.FloatField(verbose_name='Ставка'),
        ),
    ]
