# Generated by Django 4.0.1 on 2022-02-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_alter_employee_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bar_bonus',
            field=models.FloatField(default=0, verbose_name='Процент от бара'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Процент от кассы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.IntegerField(verbose_name='Ставка'),
        ),
    ]
