# Generated by Django 4.0.1 on 2022-02-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0014_employee_bar_bonus_alter_employee_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Статус в базе')),
            ],
            options={
                'verbose_name': 'Статус в базе',
                'verbose_name_plural': 'Статусы в базе',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.BooleanField(default=False, verbose_name='На смене/выходной'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.category'),
        ),
    ]
