# Generated by Django 4.0.1 on 2022-02-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0015_category_alter_employee_employee_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.category', verbose_name='Статус работника'),
        ),
    ]
