# Generated by Django 4.0.1 on 2022-02-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0016_jobposition_alter_employee_job_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['title'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Список должностей'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.jobposition', verbose_name='Должность работника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=64, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Должность работника'),
        ),
    ]
